import type { ScopeSummary } from './models';

export const seedData: ScopeSummary = {
  title: "RFP Scope for St. Regis Hotel & Residences Nashville",
  channels: ["Digital"],
  markets: ["US"],
  complexity: "Medium",
  totalPlannedHours: 4012,
  modules: [
    {
      id: "brand-strategy",
      title: "Brand Strategy",
      department: "Strategy",
      valueStatement: "Define market positioning for St. Regis Hotel & Residences Nashville across hospitality and branded residential.",
      effort: { size: "L", hoursMin: 400, hoursMax: 600 },
      phase: "Discovery",
      outputs: [
        { id: "pos", label: "Positioning" },
        { id: "masterbrand", label: "Masterbrand system" },
        { id: "messaging", label: "Messaging framework" },
        { id: "content-specs", label: "Content/specs" },
      ],
      activities: [
        "Define market positioning across hospitality and branded residential segments",
        "Create dual masterbrand system reflecting tower architecture/interiors",
        "Develop messaging framework for hotel and residential audiences",
        "Produce content specifications and partner oversight guidelines",
      ],
      risks: ["Stakeholder alignment across hotel and residential divisions"],
      assumptions: ["Access to architecture and interior design briefs", "Stakeholder availability for workshops"],
      dependencies: [{ id: "campaign-creative", type: "feeds" }],
      roles: [
        { role: "Strategist", seniority: "Sr", hours: 240 },
        { role: "Account Manager", seniority: "Mid", hours: 120 },
      ],
    },
    {
      id: "brand-identity",
      title: "Brand Identity",
      department: "Creative",
      valueStatement: "Create a dual masterbrand identity for the tower that reflects St. Regis heritage and Nashville architecture.",
      effort: { size: "L", hoursMin: 500, hoursMax: 700 },
      phase: "Concept",
      outputs: [
        { id: "logo", label: "Logo system" },
        { id: "color", label: "Color palette" },
        { id: "typography", label: "Typography" },
        { id: "imagery", label: "Imagery style" },
      ],
      activities: [
        "Design logo exploration (6-8 directions) with client review cycles",
        "Develop color palette with digital and print applications",
        "Define typography system across brand touchpoints",
        "Create imagery style guide with photo direction",
      ],
      risks: ["Multiple stakeholder approvals may extend timeline"],
      assumptions: ["Brand strategy deliverables approved before starting", "Two rounds of client revisions budgeted"],
      dependencies: [{ id: "brand-strategy", type: "needs" }],
      roles: [
        { role: "Creative Director", seniority: "Sr", hours: 200 },
        { role: "Designer", seniority: "Mid", hours: 360 },
      ],
    },
    {
      id: "brand-architecture",
      title: "Brand Architecture & Naming",
      department: "Strategy",
      valueStatement: "Establish cohesive framework spanning hotel, residences, and amenities with naming territories.",
      effort: { size: "M", hoursMin: 250, hoursMax: 400 },
      phase: "Discovery",
      outputs: [
        { id: "architecture", label: "Brand architecture framework" },
        { id: "naming", label: "Naming territories" },
        { id: "restaurant", label: "Restaurant naming" },
        { id: "amenities", label: "Amenity naming" },
      ],
      activities: [
        "Map brand architecture across hotel, residences, and sub-brands",
        "Generate naming territories and shortlists for signature venues",
        "Develop naming for restaurant, bars, spa, and resident club areas",
        "Conduct trademark screening and legal review",
      ],
      risks: ["Trademark conflicts requiring backup names"],
      assumptions: ["Legal team available for trademark screening"],
      dependencies: [{ id: "brand-strategy", type: "needs" }],
      roles: [
        { role: "Strategist", seniority: "Sr", hours: 180 },
        { role: "Copywriter", seniority: "Mid", hours: 160 },
      ],
    },
    {
      id: "experiential-activation",
      title: "Experiential Activation",
      department: "Creative",
      valueStatement: "Design the sales + marketing center experience using immersive technologies to drive pre-sales.",
      effort: { size: "L", hoursMin: 450, hoursMax: 650 },
      phase: "Production",
      outputs: [
        { id: "center-design", label: "Center experience design" },
        { id: "content-platform", label: "Content platform" },
        { id: "partner-oversight", label: "Partner oversight" },
      ],
      activities: [
        "Design sales center experience with immersive tech integration",
        "Produce content and digital platform for multi-channel activation",
        "Provide partner oversight for installation and operations",
        "Create buyer journey touchpoints from pre-sales to closing",
      ],
      risks: ["Tech partner integration complexity", "Installation timeline dependencies"],
      assumptions: ["Physical space design finalized before content production"],
      dependencies: [{ id: "brand-identity", type: "needs" }],
      roles: [
        { role: "Experience Designer", seniority: "Sr", hours: 240 },
        { role: "Developer", seniority: "Mid", hours: 280 },
      ],
    },
    {
      id: "campaign-creative",
      title: "Campaign Creative",
      department: "Creative",
      valueStatement: "Develop an opening campaign platform with headline and taglines for hotel and residential audiences.",
      effort: { size: "M", hoursMin: 300, hoursMax: 450 },
      phase: "Concept",
      outputs: [
        { id: "platform", label: "Campaign platform" },
        { id: "headline", label: "Headline" },
        { id: "taglines", label: "Taglines (hotel & residential)" },
      ],
      activities: [
        "Develop campaign platform and messaging architecture",
        "Create headline and supporting taglines for dual audiences",
        "Translate platform into multi-channel toolkits for partners",
        "Design visual identity system for campaign execution",
      ],
      risks: ["Differentiation between hotel and residential messaging"],
      assumptions: ["Brand strategy and positioning finalized"],
      dependencies: [{ id: "brand-strategy", type: "needs" }],
      roles: [
        { role: "Copywriter", seniority: "Sr", hours: 200 },
        { role: "Creative Director", seniority: "Sr", hours: 120 },
      ],
    },
    {
      id: "content-production",
      title: "Content Production (Video/Audio/Stills)",
      department: "Production",
      valueStatement: "Produce flagship brand film and photo/video assets that elevate storytelling beyond typical real-estate content.",
      effort: { size: "L", hoursMin: 600, hoursMax: 800 },
      phase: "Production",
      outputs: [
        { id: "brand-film", label: "Flagship brand film" },
        { id: "photo-suite", label: "Photo/video asset suite" },
        { id: "unreal-cg", label: "Unreal/CG renders" },
      ],
      activities: [
        "Produce flagship brand film with live-action and motion graphics",
        "Create photo and video asset library for all marketing touchpoints",
        "Develop Unreal Engine / CG renders for architectural visualization",
        "Deliver final assets in multiple formats for digital and print",
      ],
      risks: ["Weather dependencies for exterior shoots", "Post-production timeline"],
      assumptions: ["Architecture renderings available from developer team"],
      dependencies: [{ id: "campaign-creative", type: "needs" }],
      roles: [
        { role: "Producer", seniority: "Sr", hours: 280 },
        { role: "Motion Designer", seniority: "Mid", hours: 320 },
      ],
    },
    {
      id: "marketing-collateral",
      title: "Marketing Collateral & Sales Tools",
      department: "Creative",
      valueStatement: "Design premium collateral supporting buyer decisioning and brand immersion for hotel and residential sales.",
      effort: { size: "M", hoursMin: 350, hoursMax: 500 },
      phase: "Production",
      outputs: [
        { id: "collateral", label: "Premium collateral" },
        { id: "sales-tools", label: "Sales tools" },
        { id: "gift-kits", label: "Buyer merchandise/gift kits" },
      ],
      activities: [
        "Design premium collateral for buyer decisioning (brochures, spec sheets)",
        "Create sales tools for agent and partner use",
        "Develop buyer merchandise and gift kits aligned to brand",
        "Manage sourcing and production for printed materials",
      ],
      risks: ["Print production lead times", "Vendor coordination"],
      assumptions: ["Final photography available before production"],
      dependencies: [{ id: "content-production", type: "needs" }],
      roles: [
        { role: "Designer", seniority: "Mid", hours: 280 },
        { role: "Producer", seniority: "Mid", hours: 160 },
      ],
    },
    {
      id: "program-management",
      title: "Program Management & Timeline",
      department: "Operations",
      valueStatement: "Orchestrate integrated schedule aligned to construction and sales milestones with rigorous approvals.",
      effort: { size: "M", hoursMin: 200, hoursMax: 350 },
      phase: "Discovery",
      outputs: [
        { id: "integrated-schedule", label: "Integrated schedule" },
        { id: "budget-tracking", label: "Budget tracking" },
        { id: "stakeholder-comms", label: "Stakeholder communications" },
      ],
      activities: [
        "Develop integrated schedule tied to construction and sales milestones",
        "Maintain budget, risks, and stakeholder communication plan",
        "Coordinate approvals across hotel and residential stakeholders",
        "Track deliverable progress and manage vendor/partner coordination",
      ],
      risks: ["Stakeholder availability for approvals"],
      assumptions: ["Weekly status meetings with core team"],
      roles: [
        { role: "Project Manager", seniority: "Sr", hours: 280 },
      ],
    },
  ],
};
